### ISSUE TITLE
Adding ticks to one, of more than one Graphs aligned in a layout, mis-aligns them

### ISSUE THREAD

**Issue by OlyDLG** [kivy-garden/garden.graph#28]
And the magnitude of the mis-alignment increases with the length of the tick labels: the attached screenshots are of a simplified (only two graphs in a vertical box layout that typically contains at least 7 or 8) version of a "multi-graph" app I'm writing for work. You'll see that when there are no ticks, the right edges of the graphs are aligned, which is the desired final state. However, merely adding ticks causes the right edges to be mis-aligned. Moreover, as the further screenshots illustrate, as the length of the tick labels increases, so does the magnitude of the mis-alignment. This makes the multi-graph unpresentable in a professional context, and thus, IMO, constitutes a serious shortcoming, if not an out-and-out "bug."

Environment:
Windows 7 Pro SP1 64-bit
Kivy 1.8.0, KivyPy3_3

![integratorwoticks](https://cloud.githubusercontent.com/assets/6315019/7058090/fe7f973c-de11-11e4-919f-dd5cf6076a58.PNG)
![integratord10](https://cloud.githubusercontent.com/assets/6315019/7058098/087981e4-de12-11e4-8559-465b53446103.PNG)
![integratorm10](https://cloud.githubusercontent.com/assets/6315019/7058100/1206791a-de12-11e4-9f01-a50ad1773697.PNG)
![integratorm1000](https://cloud.githubusercontent.com/assets/6315019/7058102/17a1b4b6-de12-11e4-8b49-4d89b9037a01.PNG)

**Comment by OlyDLG** [comment]
OK, a minimal code sample was requested on the IRC, so here it is:

    from kivy.app import App
    from kivy.uix.boxlayout import BoxLayout
    from kivy.garden.graph import *

    graph_theme = {'y_grid_label': True,
                               'size_hint_x': 1}

    class Minimal(BoxLayout):

        def __init__(self, **kwargs):
            super(Minimal, self).__init__(**kwargs)
            self.orientation = 'vertical'
            for i in (0, 1):
                x_grid_label = i
                size_hint_y = 0.5 if i else 1.0
                G = Graph(ylabel=str(i),
                          x_grid_label=x_grid_label,
    #                    x_ticks_major=i,
                          size_hint_y=size_hint_y,
                          padding=1,
                          precision='%0.0f',
                          **graph_theme)
                self.add_widget(G)

    class MinimalApp(App):

        def build(self):
            return Minimal()

    if __name__ == '__main__':
        MinimalApp().run()

Here is the result as is:

![minimalwoutticks](https://cloud.githubusercontent.com/assets/6315019/7082145/80b0a75e-df03-11e4-9bc1-4e433f7a7ad6.PNG)

Here is the result with Line #32 uncommented:

![minimalw32](https://cloud.githubusercontent.com/assets/6315019/7082159/c9c63238-df03-11e4-8154-005ece037404.PNG)

I rest my case.

**Comment by matham** [comment]
When I asked for example code, it was not showing the issue, it was specifically showing that you still have the issue using the sample code I posted that should have fixed the issue.

**Comment by matham** [comment]
In fact a simple copy/paste from the example code to make it work for your situation shows that it fixes the issue.

```py
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.garden.graph import *
from kivy.properties import ObjectProperty, ListProperty, DictProperty
from kivy.clock import Clock

graph_theme = {'y_grid_label': True, 'size_hint_x': 1}


class SubplottedGraph(Graph):

    subplots_container = ObjectProperty(None)

    plot_area_size = ObjectProperty(None)

    def _redraw_size(self, *args):
        self.plot_area_size = self._update_labels()
        self.subplots_container.finish_redraw_trigger()

    def _finish_redraw_size(self, size):
        self._plot_area.pos = (size[0], size[1])
        self._plot_area.size = (size[2] - size[0], size[3] - size[1])
        self._fbo.size = self.size
        self._fbo_rect.texture = self._fbo.texture
        self._fbo_rect.size = self.size
        self._fbo_rect.pos = self.pos
        self._background_rect.size = self.size
        self._update_ticks(size)
        self._update_plots(size)


class Minimal(BoxLayout):

    finish_redraw_trigger = None

    def __init__(self, **kwargs):
        super(Minimal, self).__init__(**kwargs)
        self.finish_redraw_trigger = Clock.create_trigger(
            self._finish_plot_redraw)
        self.orientation = 'vertical'
        for i in (0, 1):
            x_grid_label = i
            size_hint_y = 0.5 if i else 1.0
            G = SubplottedGraph(
                subplots_container=self,
                ylabel=str(i),
                x_grid_label=x_grid_label,
                x_ticks_major=i,
                size_hint_y=size_hint_y,
                padding=1,
                precision='%0.0f',
                **graph_theme)
            self.add_widget(G)

    def _finish_plot_redraw(self, *largs):
        graphs = self.children
        x1 = max([g.plot_area_size[0] for g in graphs if g.plot_area_size is not None])
        x2 = min([g.plot_area_size[2] for g in graphs if g.plot_area_size is not None])
        for graph in graphs:
            if graph.plot_area_size is None:
                continue
            _, y1, _, y2 = graph.plot_area_size
            graph._finish_redraw_size((x1, y1, x2, y2))


class MinimalApp(App):

    def build(self):
        return Minimal()

if __name__ == '__main__':
    MinimalApp().run()

```

**Comment by OlyDLG** [comment]
That's not what I recall you posting: where did you say you posted it?
Thanks.

DLG

On Thursday, April 9, 2015, matham <notifications@github.com> wrote:

> In fact a simple copy/paste from the example code to make it work for your
> situation shows that it fixes the issue.
>
> from kivy.app import Appfrom kivy.uix.boxlayout import BoxLayoutfrom kivy.garden.graph import *from kivy.properties import ObjectProperty, ListProperty, DictPropertyfrom kivy.clock import Clock
>
> graph_theme = {'y_grid_label': True, 'size_hint_x': 1}
>
> class SubplottedGraph(Graph):
>
>     subplots_container = ObjectProperty(None)
>
>     plot_area_size = ObjectProperty(None)
>
>     def _redraw_size(self, *args):
>         self.plot_area_size = self._update_labels()
>         self.subplots_container.finish_redraw_trigger()
>
>     def _finish_redraw_size(self, size):
>         self._plot_area.pos = (size[0], size[1])
>         self._plot_area.size = (size[2] - size[0], size[3] - size[1])
>         self._fbo.size = self.size
>         self._fbo_rect.texture = self._fbo.texture
>         self._fbo_rect.size = self.size
>         self._fbo_rect.pos = self.pos
>         self._background_rect.size = self.size
>         self._update_ticks(size)
>         self._update_plots(size)
>
> class Minimal(BoxLayout):
>
>     finish_redraw_trigger = None
>
>     def __init__(self, **kwargs):
>         super(Minimal, self).__init__(**kwargs)
>         self.finish_redraw_trigger = Clock.create_trigger(
>             self._finish_plot_redraw)
>         self.orientation = 'vertical'
>         for i in (0, 1):
>             x_grid_label = i
>             size_hint_y = 0.5 if i else 1.0
>             G = SubplottedGraph(
>                 subplots_container=self,
>                 ylabel=str(i),
>                 x_grid_label=x_grid_label,
>                 x_ticks_major=i,
>                 size_hint_y=size_hint_y,
>                 padding=1,
>                 precision='%0.0f',
>                 **graph_theme)
>             self.add_widget(G)
>
>     def _finish_plot_redraw(self, *largs):
>         graphs = self.children
>         x1 = max([g.plot_area_size[0] for g in graphs if g.plot_area_size is not None])
>         x2 = min([g.plot_area_size[2] for g in graphs if g.plot_area_size is not None])
>         for graph in graphs:
>             if graph.plot_area_size is None:
>                 continue
>             _, y1, _, y2 = graph.plot_area_size
>             graph._finish_redraw_size((x1, y1, x2, y2))
>
> class MinimalApp(App):
>
>     def build(self):
>         return Minimal()
> if __name__ == '__main__':
>     MinimalApp().run()
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kivy-garden/garden.graph/issues/28#issuecomment-91435269>
> .
>


-- 
David Lawrence Goldsmith (DLG)
Software Engineer
Fishery Resource Analysis and Monitoring Division
Northwest Fisheries Science Center – NOAA
2725 Montlake Blvd E.
Seattle, WA 98112
(206) 302-2420 <%28206%29%20860-3341> (w)
(360) 481-3800 (c)

**Comment by OlyDLG** [comment]
No screen shots?

On Thursday, April 9, 2015, matham <notifications@github.com> wrote:

> In fact a simple copy/paste from the example code to make it work for your
> situation shows that it fixes the issue.
>
> from kivy.app import Appfrom kivy.uix.boxlayout import BoxLayoutfrom kivy.garden.graph import *from kivy.properties import ObjectProperty, ListProperty, DictPropertyfrom kivy.clock import Clock
>
> graph_theme = {'y_grid_label': True, 'size_hint_x': 1}
>
> class SubplottedGraph(Graph):
>
>     subplots_container = ObjectProperty(None)
>
>     plot_area_size = ObjectProperty(None)
>
>     def _redraw_size(self, *args):
>         self.plot_area_size = self._update_labels()
>         self.subplots_container.finish_redraw_trigger()
>
>     def _finish_redraw_size(self, size):
>         self._plot_area.pos = (size[0], size[1])
>         self._plot_area.size = (size[2] - size[0], size[3] - size[1])
>         self._fbo.size = self.size
>         self._fbo_rect.texture = self._fbo.texture
>         self._fbo_rect.size = self.size
>         self._fbo_rect.pos = self.pos
>         self._background_rect.size = self.size
>         self._update_ticks(size)
>         self._update_plots(size)
>
> class Minimal(BoxLayout):
>
>     finish_redraw_trigger = None
>
>     def __init__(self, **kwargs):
>         super(Minimal, self).__init__(**kwargs)
>         self.finish_redraw_trigger = Clock.create_trigger(
>             self._finish_plot_redraw)
>         self.orientation = 'vertical'
>         for i in (0, 1):
>             x_grid_label = i
>             size_hint_y = 0.5 if i else 1.0
>             G = SubplottedGraph(
>                 subplots_container=self,
>                 ylabel=str(i),
>                 x_grid_label=x_grid_label,
>                 x_ticks_major=i,
>                 size_hint_y=size_hint_y,
>                 padding=1,
>                 precision='%0.0f',
>                 **graph_theme)
>             self.add_widget(G)
>
>     def _finish_plot_redraw(self, *largs):
>         graphs = self.children
>         x1 = max([g.plot_area_size[0] for g in graphs if g.plot_area_size is not None])
>         x2 = min([g.plot_area_size[2] for g in graphs if g.plot_area_size is not None])
>         for graph in graphs:
>             if graph.plot_area_size is None:
>                 continue
>             _, y1, _, y2 = graph.plot_area_size
>             graph._finish_redraw_size((x1, y1, x2, y2))
>
> class MinimalApp(App):
>
>     def build(self):
>         return Minimal()
> if __name__ == '__main__':
>     MinimalApp().run()
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kivy-garden/garden.graph/issues/28#issuecomment-91435269>
> .
>


-- 
David Lawrence Goldsmith (DLG)
Software Engineer
Fishery Resource Analysis and Monitoring Division
Northwest Fisheries Science Center – NOAA
2725 Montlake Blvd E.
Seattle, WA 98112
(206) 302-2420 <%28206%29%20860-3341> (w)
(360) 481-3800 (c)

**Comment by matham** [comment]
Of course I did not post the exact code I posted above before. The code above comes about by adapting the example code that I did post before and again two days ago on irc (https://botbot.me/freenode/kivy/2015-04-09/?msg=36175131&page=1). It should have been quite trivial to go from the example code to the code I posted above.

As for screenshots why don't you run it?

**Comment by dessant** [comment]
@OlyDLG perhaps the question is, why should he create screenshots on top of spending time on giving you the readily fixed code?

**Comment by dessant** [comment]
@matham this reminds me of a homeless guy who asked for food and my mom made him a sandwich, his reaction was: where is the onion? :D

**Comment by OlyDLG** [comment]
Thanks, that works.  Now if I only understood half of what you added (which exactly doubled the number of substantive lines of Python code I posted--from 28 to 56: I'd hardly call that "trivial," especially when most of the stuff you added are things like _fbo properties and finish_redraw_trigger--I have no idea what that s$&t is.)

@dessant: Sorry, I don't think your analogy is valid: in that case, the homeless person at least still has their basic needs met.  I'm more like a cooking student being required to make Chicken Divan, given all the tools and ingredients, but no recipe, and the instructor says "here you go; it should be obvious how to prepare the dish."  Most of the stuff matham added is still foreign to me.  But he has my thanks nevertheless.

**Comment by matham** [comment]
dude, all of that `_fbo properties` stuff is a copy paste from the gist I posted before. You don't need to know anything about that to adapt it to your example from the example I posted.

**Comment by OlyDLG** [comment]
OK, now the graphs are aligned, but the x-axis ticks and their labels are messed up: all the graphs but the the bottom one aren't supposed to have ticks--and didn't before I incorporated your code, but now do--and the bottom ticks are supposed to have labels, and did before I incorporated your code but now don't.  Any ideas what about your code might have changed those properties?

**Comment by matham** [comment]
I think we can close this now.
