### ISSUE TITLE
Aviod joining two strokes of drawing

### ISSUE THREAD

**Issue by rsshruti** [kivy-garden/garden.graph#31]
Hi, I am plotting a graph reading a file with x, y positions. These drawings are in form of letters(y, c etc).
In actual drawing there is a gap (visually) in the strokes of letters, but when i am making a graph using kivy garden. It is somehow joining the two strokes with a line.

In the attached pic, you can see there are two strokes of y, one is small (first one) and second is remaining full y. Both two strokes are attached by a straight line (approx pos: 600, -80).

How can I avoid this?

Thanks in advance! Quiet new in kivy!  

![mis1](https://cloud.githubusercontent.com/assets/4377956/8460529/364d1e76-201d-11e5-8ac2-6d223c006fb3.png)

**Comment by rsshruti** [comment]
Problem solved. Updated code
num = 0
        point = []
        point_list = []  
        flag = False
        for stroke in curr_data: 
            
            print '+++++++++++++++++++++++++++',stroke
            
            num += 1 
            
           
            graph = Graph(xlabel='X', ylabel='Y', x_ticks_major = 50, y_ticks_major = 20, y_grid_label = True, x_grid_label = True, padding = 5,
            x_grid = False, y_grid=True, xmin = 500, xmax = 800, ymin=180, ymax=50, draw_border =  True)
            
            
            plot = MeshLinePlot(color=[1, 0, 0, 1])            
            plot.points = stroke
        
            graph.pos = 30,120
            graph.size = 400,400
            self.add_widget(graph)
            graph.add_plot(plot)     #    
            print num

**Comment by matham** [comment]
Yep, you need to create different plots for each character, otherwise it'd be connected.
