### ISSUE TITLE
HOW TO PLOT GRAPH WITH DELAY IN EVERY POINT?

### ISSUE THREAD

**Issue by rsshruti** [kivy-garden/garden.graph#32]
Hi,

is it possible to plot graph point by point, so that it looks like someone is drawing instead of displaying all points together?

**Comment by matham** [comment]
There's no automated way to do this. However, you can simulate it by manually adding new points periodically.

**Comment by rsshruti** [comment]
Thanks! I tried few things, every time kivy window is taking a lot of time in opening. And in the end, it is displaying all the points together. I posted my code here, could anyone look at it?



def draw(self, curr_data):
        
        num = 0        
        point_list = []        
        for stroke in curr_data: 
           
            graph = Graph(padding = 20, xmin = 500, xmax = 800, ymin = 180, ymax = 30, draw_border = True)           
            
            plot = LinePlot(color=[1, 1, 0, 1], line_width = 2)            
            #for pix in stroke:
            plot.points = stroke
            graph.add_plot(plot)     
            graph.pos = 30,120
            graph.size = 400,400
            self.add_widget(graph)
            time.sleep(1.0)

**Comment by matham** [comment]
Ok, yes, there are some issues with your code; mainly that it blocks the kivy thread. You need to add the points using clock callbacks. I suggest that you go through the kivy docs and demos to understand how kivy's arch functions. Also, for direct help you should join us on #kivy on IRC. It's difficult to do this over github issues.
